name: Test and Coverage

on:
  push:
    branches:
      - main # Adjust to your main branch name
  pull_request:
    branches:
      - main # Adjust to your main branch name

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x # Choose your Python version

      - name: Install dependencies
        run: pip install -r requirements.txt # Replace with your dependencies file

      - name: Run tests with coverage
        run: |
          pip install coverage
          coverage run -m unittest discover -s test
        continue-on-error: true # Continue even if tests fail

      - name: Generate coverage report
        run: coverage report -m

      - name: Upload coverage to Coveralls
        if: success()
        run: pip install coveralls && coveralls
